In [3]:
import pandas as pd
df = pd.read_csv('data/district_migration.csv',delimiter=',')

In [4]:
df

,lgd_state_id,lgd_district_id,inltmigrantstotal,inltmigrationrate,inltmigrationshare,instmigrantstotal,instmigrationrate,instmigrationshare,outltmigrantstotal,outltmigrationrate,outltmigrationshare,outstmigrantstotal,outstmigrationrate,outstmigrationshare
0,1,1,8185802.0,0.003257,0.000429,10900000.0,0.000427,0.000042,8185802,0.001612,0.000213,10900000,0.010254,0.001018
1,1,2,8185802.0,0.001551,0.000143,10900000.0,0.001404,0.000097,8185802,0.002037,0.000188,10900000,0.001185,0.000082
2,1,3,8185802.0,0.003776,0.000465,10900000.0,0.000195,0.000018,8185802,0.001823,0.000225,10900000,0.002970,0.000276
3,1,4,8185802.0,0.001203,0.000060,10900000.0,0.000942,0.000036,8185802,0.005440,0.000272,10900000,0.007058,0.000266
4,1,5,8185802.0,0.005552,0.001038,10900000.0,0.015447,0.002176,8185802,0.004726,0.000883,10900000,0.001060,0.000149
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
726,36,700,8185802.0,0.014595,0.003985,10900000.0,0.021054,0.004332,8185802,0.001231,0.000336,10900000,0.001005,0.000207
727,36,720,8185802.0,0.002948,0.000098,10900000.0,0.001849,0.000046,8185802,0.004200,0.000139,10900000,0.002167,0.000054
728,36,721,8185802.0,0.001635,0.000128,10900000.0,0.001930,0.000114,8185802,0.004477,0.000350,10900000,0.013474,0.000793
729,37,6,8185802.0,0.000433,0.000007,10900000.0,0.005456,0.000071,8185802,0.001697,0.000029,10900000,0.000000,0.000000
730,37,9,8185802.0,0.000427,0.000007,10900000.0,0.006163,0.000076,8185802,0.006820,0.000111,10900000,0.000000,0.000000